name: SupportServer
main: com.example.SupportServer
version: 1.0
api-version: 1.21
depend: [ProtocolLib] 
commands:
  supportserver:
    description: Reload plugin configuration
    usage: /supportserver reload
permissions:
  Sunflower.SP.admin:
    description: Admin permissions for Support Server
    default: op 