name: ComBat
main: ComBat.Main_plugin
version: 1.0
api-version: 1.21
depend: [ProtocolLib] 
commands:
  ComBat:
    description: Reload plugin configuration
    usage: /ComBat reload
permissions:
  Sunflower.SP.admin:
    description: Admin permissions for Support Server
    default: op 